# Generated by Django 4.2 on 2024-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('Sum', 'Sum'), ('Rub', 'Rub'), ('$', '$')], default='Sum', max_length=10),
        ),
    ]
